# Generated by Django 4.2.2 on 2023-12-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_performance_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='delivery_date',
            new_name='expected_delivery_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivered_date',
            field=models.DateTimeField(null=True),
        ),
    ]
