# Generated by Django 5.0 on 2023-12-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_purchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='quality_rating_avg',
            field=models.FloatField(null=True),
        ),
    ]
